name: Release Backend

on:
  push:
    tags:
      - "v*"

jobs:
  notify-main-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.MAIN_REPO_TOKEN }}
          repository: youruser/portfolio
          event-type: backend-release
          client-payload: '{"version": "${{ github.ref_name }}"}'
